### PR TITLE
Fix broken long urls in reference section of article page

### PR DESCRIPTION
**Pull request by israelcefrin**
Hi @NateWr , I´ve created a branch dedicate to fix only the long url breaking issue. I´m sorry for the mess, but the first time I did everything in browser and I was not used to it. I followed the regular workflow you suggested and I hope it´s everything fine now.
I am using the CSS from here: https://github.com/pkp/pkp-docs/pull/263/files as you suggested.

Please, let me know whether I should close the other PR.

### CODE REVIEW

**Comment by israelcefrin** [comment]
@NateWr I´ve removed from my branch all that mess and left only the fix. I think it´s going to work correctly now. Thanks!

**Comment by NateWr** [comment]
It looks like you may have gotten the wires crossed here. The code in this PR deals with the subject section and doesn't add the CSS code.

**Comment by israelcefrin** [comment]
Hi @NateWr , CSS code added (and the other chunk removed).

**Comment by NateWr** [comment]
Thanks! :+1:

**Pull request merged**
