### PR TITLE
Spanish translation of Bootstrap 3 Base

### PR DESCRIPTION
**Pull request by kant**
Translation done to support this OJS theme

### CODE REVIEW

**Comment by NateWr** [comment]
@mtub would you be able to sign off on this?

**Comment by mtub** [comment]
Looks okay, but better have @marcbria have a look at the first 10 lines…

**Comment by marcbria** [comment]
@mtub I think we also translated this plugin, but this translation is also good so I think the best choice is merging this till we overwrite all the es_ES with the last delivery. Do you agree?

**Comment by mtub** [comment]
@NateWr, go ahead with merging. (If you granted me write access, I could do it myself.)

**Comment by NateWr** [comment]
Thanks everyone!

**Pull request merged**
