### PR TITLE
Addition of keywords in article detail page

### PR DESCRIPTION
**Pull request by anupent**

### CODE REVIEW

**Comment by NateWr** [comment]
Thanks @anupent! The markup looks like it's come straight from the default theme. It doesn't translate very well into the bootstrap theme. Here's what it looks like for me:

selection_039

If the keywords are going to be displayed there, they should probably be put inside of a `.panel` element, like the How to Cite content. Or, they could be put under the DOI on the left.

selection_040

Would you be able to update to match one of those?

**Comment by anupent** [comment]
Can you check this commit?

**Comment by NateWr** [comment]
Looks great! :+1:

**Comment by NateWr** [comment]
ps - if you've got any energy to do some more, I just filed this issue: https://github.com/NateWr/bootstrap3/issues/94

**Pull request merged**
